# Generated by Django 3.2 on 2023-11-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_auto_20231019_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Fecha',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
    ]
