# Generated by Django 3.2 on 2023-11-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0004_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Fecha',
            new_name='Promo',
        ),
    ]
