# Generated by Django 3.2 on 2023-11-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_rename_fecha_libro_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='Promo',
            field=models.BooleanField(null=True, verbose_name='Promo'),
        ),
    ]
